# Generated by Django 5.0.1 on 2024-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamousPerson',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('occupation', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=2)),
                ('alive', models.BooleanField(blank=True)),
                ('bplace_name', models.CharField(blank=True, max_length=2000)),
                ('bplace_country', models.CharField(blank=True, max_length=255)),
                ('birthdate', models.DateField(blank=True)),
                ('birthyear', models.IntegerField(blank=True)),
                ('dplace_name', models.CharField(blank=True, max_length=2000)),
                ('dplace_country', models.CharField(blank=True, max_length=255)),
                ('deathdate', models.DateField(blank=True)),
                ('deathyear', models.IntegerField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('hpi', models.FloatField()),
            ],
        ),
    ]
