# Generated by Django 5.0.1 on 2024-02-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contemporaries_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='famousperson',
            table='pantheon',
        ),
    ]
