# Generated by Django 5.0.1 on 2024-02-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contemporaries_app', '0002_alter_famousperson_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famousperson',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='famousperson',
            name='alive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='famousperson',
            name='birthdate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='famousperson',
            name='birthyear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='famousperson',
            name='bplace_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='famousperson',
            name='bplace_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='famousperson',
            name='deathdate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='famousperson',
            name='deathyear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='famousperson',
            name='dplace_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='famousperson',
            name='dplace_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterModelTable(
            name='famousperson',
            table=None,
        ),
    ]
